import torch
import torch.nn as nn

class TripletLoss(nn.Module):
    """
    Triplet loss function with Online Hard Example Mining (OHEM).
    """
    def __init__(self, margin=0.3):
        super(TripletLoss, self).__init__()
        self.margin = margin
        self.ranking_loss = nn.MarginRankingLoss(margin=margin)

    def forward(self, inputs, targets):
        """
        inputs: Feature representations from the backbone network (Batch_Size, Feature_Dim)
        targets: Ground truth identity labels (Batch_Size)
        """
        # Must convert to FP32 to prevent overflow in mixed precision training
        inputs = inputs.float()
        n = inputs.size(0)
        
        # Use PyTorch's highly optimized cdist to calculate Euclidean distance
        dist = torch.cdist(inputs, inputs, p=2.0)

        # Generate a mask to distinguish positive samples (same ID) and negative samples (different ID)
        mask = targets.expand(n, n).eq(targets.expand(n, n).t())
        dist_ap, dist_an = [], []

        # Hard example mining: Find the hardest positive and hardest negative for each Anchor
        for i in range(n):
            # Hardest Positive (farthest sample of the same class)
            dist_ap.append(dist[i][mask[i]].max().unsqueeze(0))  
            # Hardest Negative (closest sample of a different class)
            dist_an.append(dist[i][mask[i] == 0].min().unsqueeze(0)) 

        dist_ap = torch.cat(dist_ap)
        dist_an = torch.cat(dist_an)

        # Calculate Margin Ranking Loss
        y = torch.ones_like(dist_an)
        loss = self.ranking_loss(dist_an, dist_ap, y)
        return loss


def test_dual_loss_module():
    print("=> 🚀 Starting Dual Loss Test (ID Loss + Triplet Loss)\n")

    batch_size = 16       # Simulated Batch Size
    num_classes = 100     # Simulated total number of identity IDs (classes)
    feature_dim = 2048    # Simulated feature dimension from ResNet50 (i.e., vbase)

    # Simulate labels generated by the PK sampler (P=4 IDs, K=4 images per ID)
    # Example labels: [0,0,0,0, 1,1,1,1, 2,2,2,2, 3,3,3,3]
    labels = torch.tensor([0]*4 + [1]*4 + [2]*4 + [3]*4, dtype=torch.long)
    print(f"1. Simulated Batch Labels (PK Sampling): \n   {labels.tolist()}")

    # Simulate model output 1: logits (used for classification prediction, output after fully connected layer)
    logits = torch.randn(batch_size, num_classes)
    
    # Simulate model output 2: features (used for feature distance calculation, usually vbase after GAP)
    # Apply L2 normalization to make the data distribution more like real feature representations
    features = torch.randn(batch_size, feature_dim)
    features = nn.functional.normalize(features, p=2, dim=1) 
    
    print(f"2. Simulated Logits Shape (for ID Loss): {logits.shape}")
    print(f"3. Simulated Features Shape (for Triplet Loss): {features.shape}\n")

    criterion_id = nn.CrossEntropyLoss()
    criterion_triplet = TripletLoss(margin=0.3)
    
    # Set weight ratio (1:1 here)
    weight_id = 1.0
    weight_triplet = 1.0

    # Calculate ID classification loss
    loss_id = criterion_id(logits, labels)
    
    # Calculate triplet loss with hard example mining
    loss_triplet = criterion_triplet(features, labels)

    # Combine the dual losses
    total_loss = weight_id * loss_id + weight_triplet * loss_triplet

    print("-" * 40)
    print(f"   - Classification Loss (ID Loss): {loss_id.item():.4f}")
    print(f"   - Triplet Loss:                  {loss_triplet.item():.4f}")
    print(f"   - Total Combined Loss:           {total_loss.item():.4f}")
    print("-" * 40)

    # Test if gradient backpropagation works normally (check for NaN blockages)
    try:
        total_loss.backward()
        print("\n=> [✔] Test Passed: Backpropagation executed successfully, no NaN or broken computation graphs!")
    except Exception as e:
        print(f"\n=> [!] Warning: Backpropagation failed, error message: {e}")

if __name__ == "__main__":
    torch.manual_seed(42)
    test_dual_loss_module()